spring:
  resources:
    static-locations: /WEB-INF/static/
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    druid:
      url: jdbc:h2:~/monitor;INIT=RUNSCRIPT FROM 'classpath:init.sql';USER=root;MODE=MYSQL
      username: root
      test-while-idle: false
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true

logging:
  config: classpath:log4j2.xml

mybatis:
  config-location: classpath:mybatis.xml

monitor:
  ips: 10.0.0.1, 10.0.0.2, 10.0.0.3
  fetchInteval: 10
  cleanInteval: 86400
